spring.application.name=Projekt

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=${DB_DRIVER}

spring.jpa.hibernate.ddl-auto=update

spring.profiles.active=h2
server.port=8080

jwt.secret=thisIsMySuperSecretKeyForJwtThatIsLongEnough1234567890abcdef
jwt.expiration=3600000
