spring.application.name=Projekt

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

jwt.secret=thisIsMySuperSecretKeyForJwtThatIsLongEnough1234567890abcdef
jwt.expiration=3600000
spring.profiles.active=local
server.port=8080